# Generated by Django 6.0.6 on 2026-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات درباره ما')),
                ('active_members', models.IntegerField(default=0, verbose_name='تعداد اعضای فعال')),
                ('events_held', models.IntegerField(default=0, verbose_name='تعداد رویدادهای برگزار شده')),
                ('total_resources', models.IntegerField(default=0, verbose_name='تعداد منابع علمی')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان رویداد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='تصویر')),
                ('date_jalali', models.CharField(max_length=50, verbose_name='تاریخ شمسی')),
                ('time', models.CharField(max_length=20, verbose_name='ساعت')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('is_upcoming', models.BooleanField(default=True, verbose_name='رویداد آینده')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['date_jalali'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], max_length=5, verbose_name='نوع رسانه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/', verbose_name='تصویر')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='فایل ویدیو')),
                ('caption_title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('caption_text', models.CharField(blank=True, max_length=300, verbose_name='متن پایین اسلاید')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'اسلاید گالری',
                'verbose_name_plural': 'گالری تصاویر و ویدیوها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=200, verbose_name='عنوان جشنواره یا مسابقه')),
                ('rank', models.CharField(max_length=200, verbose_name='مقام')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'افتخار',
                'verbose_name_plural': 'افتخارات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='خلاصه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='تصویر')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان منبع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/', verbose_name='فایل')),
                ('download_count', models.IntegerField(default=0, verbose_name='تعداد دانلود')),
            ],
            options={
                'verbose_name': 'منبع علمی',
                'verbose_name_plural': 'منابع علمی',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='نام پلتفرم')),
                ('url', models.URLField(verbose_name='لینک')),
                ('icon_class', models.CharField(max_length=100, verbose_name='کلاس آیکون')),
                ('is_footer', models.BooleanField(default=True, verbose_name='نمایش در فوتر')),
                ('is_floating', models.BooleanField(default=True, verbose_name='نمایش در آیکون شناور')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'لینک شبکه اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای شبکه\u200cهای اجتماعی',
                'ordering': ['order'],
            },
        ),
    ]
