# Generated by Django 4.2.7 on 2026-07-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات درباره ما")),
                (
                    "active_members",
                    models.IntegerField(default=0, verbose_name="تعداد اعضای فعال"),
                ),
                (
                    "events_held",
                    models.IntegerField(
                        default=0, verbose_name="تعداد رویدادهای برگزار شده"
                    ),
                ),
                (
                    "total_resources",
                    models.IntegerField(default=0, verbose_name="تعداد منابع علمی"),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="همین حالا به خانواده بزرگ انجمن علمی مکانیک بپیوندید",
                        max_length=200,
                        verbose_name="متن دکمه",
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        default="/login/", max_length=200, verbose_name="لینک دکمه"
                    ),
                ),
            ],
            options={
                "verbose_name": "درباره ما",
                "verbose_name_plural": "درباره ما",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "تصویر"), ("video", "ویدیو")],
                        max_length=5,
                        verbose_name="نوع رسانه",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gallery/images/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gallery/videos/",
                        verbose_name="فایل ویدیو",
                    ),
                ),
                (
                    "caption_title",
                    models.CharField(max_length=200, verbose_name="عنوان"),
                ),
                (
                    "caption_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="متن پایین اسلاید"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "اسلاید گالری",
                "verbose_name_plural": "گالری تصاویر و ویدیوها",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Honor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition_name",
                    models.CharField(
                        max_length=200, verbose_name="عنوان جشنواره یا مسابقه"
                    ),
                ),
                ("rank", models.CharField(max_length=200, verbose_name="مقام")),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="honors/",
                        verbose_name="تصویر افتخار",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در صفحه اصلی"
                    ),
                ),
            ],
            options={
                "verbose_name": "افتخار",
                "verbose_name_plural": "افتخارات",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="IndustryService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان خدمت")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="industry/",
                        verbose_name="تصویر",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام مسئول"
                    ),
                ),
                (
                    "manager_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره تماس مسئول"
                    ),
                ),
                (
                    "manager_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="ایمیل مسئول"
                    ),
                ),
                (
                    "manager_room",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="شماره اتاق"
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True, verbose_name="اهداف (هر هدف در یک خط)"
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمات صنعت",
                "verbose_name_plural": "خدمات دانشکده به صنعت",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان منبع")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resources/",
                        verbose_name="تصویر",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resources/files/",
                        verbose_name="فایل",
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="تعداد دانلود"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("آموزشی", "آموزشی"),
                            ("پژوهشی", "پژوهشی"),
                            ("صنعتی", "صنعتی"),
                            ("فناوری", "فناوری"),
                            ("بین\u200cالملل", "بین\u200cالملل"),
                            ("سایر", "سایر"),
                        ],
                        default="سایر",
                        max_length=50,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "منبع علمی",
                "verbose_name_plural": "منابع علمی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(max_length=50, verbose_name="نام پلتفرم"),
                ),
                ("url", models.URLField(verbose_name="لینک")),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کلاس آیکون"
                    ),
                ),
                (
                    "is_footer",
                    models.BooleanField(default=True, verbose_name="نمایش در فوتر"),
                ),
                (
                    "is_floating",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در آیکون شناور"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="social_icons/",
                        verbose_name="تصویر آیکون",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک شبکه اجتماعی",
                "verbose_name_plural": "لینک\u200cهای شبکه\u200cهای اجتماعی",
                "ordering": ["order"],
            },
        ),
    ]
