# Generated by Django 6.0.6 on 2026-06-18 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='button_link',
            field=models.CharField(default='/login/', max_length=200, verbose_name='لینک دکمه'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='button_text',
            field=models.CharField(default='همین حالا به خانواده بزرگ انجمن علمی مکانیک بپیوندید', max_length=200, verbose_name='متن دکمه'),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='ظرفیت'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='تکمیل شده'),
        ),
        migrations.AddField(
            model_name='event',
            name='registered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد ثبت\u200cنام\u200cها'),
        ),
        migrations.AddField(
            model_name='honor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='honors/', verbose_name='تصویر افتخار'),
        ),
        migrations.AddField(
            model_name='honor',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='تصویر آیکون'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='کلاس آیکون'),
        ),
        # migrations.CreateModel(
        #     name='Registration',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
        #         ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('attended', 'حضور یافته')], default='pending', max_length=20, verbose_name='وضعیت')),
        #         ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس')),
        #         ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
        #         ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='website.event', verbose_name='رویداد')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
        #     ],
        #     options={
        #         'verbose_name': 'ثبت\u200cنام',
        #         'verbose_name_plural': 'ثبت\u200cنام\u200cها',
        #         'ordering': ['-registration_date'],
        #         'unique_together': {('user', 'event')},
        #     },
        # ),
    ]
