# Generated by Django 4.2.30 on 2026-06-20 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "منبع علمی",
                "verbose_name_plural": "منابع علمی",
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("آموزشی", "آموزشی"),
                    ("پژوهشی", "پژوهشی"),
                    ("صنعتی", "صنعتی"),
                    ("فناوری", "فناوری"),
                    ("بین\u200cالملل", "بین\u200cالملل"),
                    ("سایر", "سایر"),
                ],
                default="سایر",
                max_length=50,
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
    ]
