# Generated by Django 6.0.6 on 2026-06-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutinfo_button_link_aboutinfo_button_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
