# Generated by Django 4.2.30 on 2026-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_aboutinfo_id_alter_galleryitem_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان خدمت")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="industry/",
                        verbose_name="تصویر",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام مسئول"
                    ),
                ),
                (
                    "manager_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره تماس مسئول"
                    ),
                ),
                (
                    "manager_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="ایمیل مسئول"
                    ),
                ),
                (
                    "manager_room",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="شماره اتاق"
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True, verbose_name="اهداف (هر هدف در یک خط)"
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمات صنعت",
                "verbose_name_plural": "خدمات دانشکده به صنعت",
                "ordering": ["order"],
            },
        ),
    ]
