# Generated by Django 4.2.30 on 2026-06-20 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره دانشجویی",
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رشته تحصیلی",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="مقطع تحصیلی"
                    ),
                ),
                (
                    "entry_year",
                    models.IntegerField(blank=True, null=True, verbose_name="سال ورود"),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ترم تحصیلی"
                    ),
                ),
                (
                    "committee",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="کمیته مورد نظر",
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="تخصص/علاقه\u200cمندی",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="درباره خود"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="students/avatars/default.png",
                        null=True,
                        upload_to="students/avatars/",
                        verbose_name="عکس پروفایل",
                    ),
                ),
                (
                    "receive_notifications",
                    models.BooleanField(default=True, verbose_name="دریافت نوتیفیکیشن"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل دانشجو",
                "verbose_name_plural": "پروفایل\u200cهای دانشجویان",
            },
        ),
    ]
