# Generated by Django 4.2.30 on 2026-06-20 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
# ❌ این خط رو حذف کن
# import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان رویداد"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/", verbose_name="تصویر"
                    ),
                ),
                ("short_description", models.TextField(verbose_name="توضیحات کوتاه")),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="توضیحات کامل"),
                ),
                (
                    "syllabus",
                    models.TextField(
                        blank=True,
                        help_text="هر سرفصل در یک خط",
                        verbose_name="سرفصل\u200cها",
                    ),
                ),
                (
                    "instructor_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام مدرس"
                    ),
                ),
                (
                    "instructor_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="عنوان مدرس"
                    ),
                ),
                (
                    "instructor_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="instructors/",
                        verbose_name="تصویر مدرس",
                    ),
                ),
                # ✅ این رو تغییر بده
                (
                    "jalali_date",
                    models.CharField(max_length=50, verbose_name="تاریخ شمسی"),
                ),
                ("time", models.CharField(max_length=20, verbose_name="ساعت")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "در حال ثبت\u200cنام"),
                            ("ongoing", "در حال برگزاری"),
                            ("completed", "به پایان رسیده"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ظرفیت (۰=نامحدود)"
                    ),
                ),
                (
                    "registered_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد ثبت\u200cنام\u200cها"
                    ),
                ),
                (
                    "is_full",
                    models.BooleanField(default=False, verbose_name="تکمیل شده"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "رویداد",
                "verbose_name_plural": "رویدادها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تأیید"),
                            ("confirmed", "تأیید شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت\u200cنام",
                "verbose_name_plural": "ثبت\u200cنام\u200cها",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_even_status_5709b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_full"], name="events_even_is_full_fa7842_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("event", "user")},
        ),
    ]