# Generated by Django 6.0.6 on 2026-06-20 09:43

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
        migrations.AlterField(
            model_name='event',
            name='jalali_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شمسی'),
        ),
    ]
