# Generated by Django 6.0.6 on 2026-06-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id_alter_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='jalali_date',
            field=models.CharField(help_text='مثال: ۱۴۰۴/۰۱/۲۰', max_length=50, verbose_name='تاریخ شمسی'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(help_text='مثال: ۱۵:۰۰', max_length=20, verbose_name='ساعت'),
        ),
    ]
