# Generated by Django 6.0.6 on 2026-06-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_jalali_date_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='jalali_date',
            field=models.CharField(blank=True, help_text='مثال: ۱۴۰۴/۰۱/۲۰', max_length=50, null=True, verbose_name='تاریخ شمسی'),
        ),
    ]
