# Generated by Django 4.2.30 on 2026-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
