# Generated by Django 6.0.6 on 2026-06-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_created_by'),
        ('events', '0008_alter_event_id_alter_registration_id'),
    ]

    operations = [
    ]
