# Generated by Django 4.2.7 on 2026-07-15 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره پرسنلی",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="دانشکده"
                    ),
                ),
                (
                    "academic_rank",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="مرتبه علمی"
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="رشته تخصصی"
                    ),
                ),
                (
                    "office_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره دفتر"
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(
                        blank=True, null=True, verbose_name="زمینه\u200cهای پژوهشی"
                    ),
                ),
                (
                    "publications",
                    models.TextField(
                        blank=True, null=True, verbose_name="مقالات و تالیفات"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="درباره خود"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="professors/avatars/default.png",
                        null=True,
                        upload_to="professors/avatars/",
                        verbose_name="عکس پروفایل",
                    ),
                ),
                (
                    "receive_notifications",
                    models.BooleanField(default=True, verbose_name="دریافت نوتیفیکیشن"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل استاد",
                "verbose_name_plural": "پروفایل\u200cهای اساتید",
            },
        ),
        migrations.CreateModel(
            name="ProfessorArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان مقاله")),
                ("abstract", models.TextField(verbose_name="چکیده مقاله")),
                (
                    "file",
                    models.FileField(
                        upload_to="professor_articles/", verbose_name="فایل مقاله (PDF)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("submitted", "ارسال شده به دبیر انجمن"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "admin_feedback",
                    models.TextField(blank=True, verbose_name="نظر دبیر انجمن"),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشنهاد مقاله",
                "verbose_name_plural": "پیشنهادات مقالات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان پیشنهادی"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "proposed_date",
                    models.CharField(
                        help_text="مثال: ۱۴۰۴/۰۲/۱۰",
                        max_length=50,
                        verbose_name="تاریخ پیشنهادی",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("کارگاه", "کارگاه"),
                            ("سمینار", "سمینار"),
                            ("نشست علمی", "نشست علمی"),
                        ],
                        max_length=50,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_feedback",
                    models.TextField(blank=True, verbose_name="نظر دبیر"),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشنهاد رویداد",
                "verbose_name_plural": "پیشنهادات رویداد",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("instructor", "مدرس"),
                            ("speaker", "سخنران"),
                            ("moderator", "مجری"),
                            ("judge", "داور"),
                        ],
                        default="instructor",
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پاسخ"),
                            ("accepted", "پذیرفته شده"),
                            ("declined", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="پیام"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor_invitations",
                        to="events.event",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "دعوتنامه رویداد",
                "verbose_name_plural": "دعوتنامه\u200cهای رویداد",
                "ordering": ["-created_at"],
                "unique_together": {("event", "professor")},
            },
        ),
    ]
