# Generated by Django 4.2.30 on 2026-06-22 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_alter_event_id_alter_registration_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره پرسنلی",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="دانشکده"
                    ),
                ),
                (
                    "academic_rank",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="مرتبه علمی"
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="رشته تخصصی"
                    ),
                ),
                (
                    "office_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره دفتر"
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(
                        blank=True, null=True, verbose_name="زمینه\u200cهای پژوهشی"
                    ),
                ),
                (
                    "publications",
                    models.TextField(
                        blank=True, null=True, verbose_name="مقالات و تالیفات"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="درباره خود"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="professors/avatars/default.png",
                        null=True,
                        upload_to="professors/avatars/",
                        verbose_name="عکس پروفایل",
                    ),
                ),
                (
                    "receive_notifications",
                    models.BooleanField(default=True, verbose_name="دریافت نوتیفیکیشن"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل استاد",
                "verbose_name_plural": "پروفایل\u200cهای اساتید",
            },
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("instructor", "مدرس"),
                            ("speaker", "سخنران"),
                            ("moderator", "مجری"),
                            ("judge", "داور"),
                        ],
                        default="instructor",
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پاسخ"),
                            ("accepted", "پذیرفته شده"),
                            ("declined", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="پیام"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor_invitations",
                        to="events.event",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "دعوتنامه رویداد",
                "verbose_name_plural": "دعوتنامه\u200cهای رویداد",
                "ordering": ["-created_at"],
                "unique_together": {("event", "professor")},
            },
        ),
    ]
