# Generated by Django 4.2.30 on 2026-06-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("professor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان مقاله")),
                ("abstract", models.TextField(verbose_name="چکیده مقاله")),
                (
                    "file",
                    models.FileField(
                        upload_to="professor_articles/", verbose_name="فایل مقاله (PDF)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("submitted", "ارسال شده به دبیر انجمن"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "admin_feedback",
                    models.TextField(blank=True, verbose_name="نظر دبیر انجمن"),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشنهاد مقاله",
                "verbose_name_plural": "پیشنهادات مقالات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان پیشنهادی"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "proposed_date",
                    models.CharField(
                        help_text="مثال: ۱۴۰۴/۰۲/۱۰",
                        max_length=50,
                        verbose_name="تاریخ پیشنهادی",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("کارگاه", "کارگاه"),
                            ("سمینار", "سمینار"),
                            ("نشست علمی", "نشست علمی"),
                        ],
                        max_length=50,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_feedback",
                    models.TextField(blank=True, verbose_name="نظر دبیر"),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشنهاد رویداد",
                "verbose_name_plural": "پیشنهادات رویداد",
                "ordering": ["-created_at"],
            },
        ),
    ]
