# Generated by Django 6.0.6 on 2026-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام متقاضی'),
        ),
    ]
