# Generated by Django 6.0.6 on 2026-06-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrequest',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
