# Generated by Django 6.0.6 on 2026-06-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_committee_id_alter_galleryimage_id_and_more'),
        ('members', '0003_alter_memberrequest_student_id'),
    ]

    operations = [
    ]
