# Generated by Django 6.0.6 on 2026-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_merge_20260627_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalresource',
            options={'ordering': ['-created_at'], 'verbose_name': 'منبع داخلی', 'verbose_name_plural': 'منابع داخلی'},
        ),
        migrations.AlterModelOptions(
            name='memberrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست عضویت', 'verbose_name_plural': 'درخواست\u200cهای عضویت'},
        ),
        migrations.AlterField(
            model_name='committee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internalresource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='student_id',
            field=models.CharField(max_length=20, verbose_name='شماره دانشجویی'),
        ),
    ]
