# Generated by Django 6.0.6 on 2026-06-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_eventinvitation_memberrequest_unique_pending_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventInvitation',
        ),
    ]
