# Generated by Django 4.2.30 on 2026-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان خبر")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="news/", verbose_name="تصویر"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="متن کوتاه برای نمایش در کارت\u200cهای خبر",
                        max_length=300,
                        verbose_name="خلاصه خبر",
                    ),
                ),
                ("content", models.TextField(verbose_name="متن کامل خبر")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("announcement", "اطلاعیه"),
                            ("event", "رویداد"),
                            ("academic", "آموزشی"),
                            ("research", "پژوهشی"),
                            ("industry", "صنعت"),
                            ("other", "سایر"),
                        ],
                        default="announcement",
                        max_length=20,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "jalali_date",
                    models.CharField(max_length=50, verbose_name="تاریخ شمسی"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شود؟"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "اخبار",
                "ordering": ["-created_at"],
            },
        ),
    ]
