# Generated by Django 6.0.6 on 2026-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='اسلاگ'),
        ),
    ]
