# Generated by Django 4.2.30 on 2026-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
